const OK_CODE = 200;
const CREATED_CODE = 201;
const ERROR_CODE = 400;
const UNAUTHORIZED_CODE = 401;
const FORBIDDEN = 403;
const NOT_FOUND_CODE = 404;
const SERVER_ERROR_CODE = 500;

export { OK_CODE, CREATED_CODE, ERROR_CODE, UNAUTHORIZED_CODE, FORBIDDEN, NOT_FOUND_CODE, SERVER_ERROR_CODE };